### PR TITLE
Create Fascinating_Num.java

### PR DESCRIPTION
**Pull request by tb-rules10**
I've added a really good Java program I hope it gets merged & you add hacktoberfest label to it.
Thnx.

### CODE REVIEW

**Review by mohdfawad99 — CHANGES_REQUESTED** [review]
Class name and file name must be same in Java. Kindly correct it.

**Comment by mohdfawad99** [comment]
Class name and file name must be same in Java. Kindly correct it and create PR again.

**Comment by tb-rules10** [comment]
I'll correct it bro atleast don't mark it invalid
I'll get disqualified if I get 2 invalid labels . please remove it.

**Comment by mohdfawad99** [comment]
sure

**Comment by tb-rules10** [comment]
I've created a new & correct pr. Plz check it

**Pull request closed without merging**
