### PR TITLE
js code added

### PR DESCRIPTION
**Pull request by sabbirshawon**

### CODE REVIEW

**Review by mohdfawad99 — APPROVED** [review]
Good

**Comment by sabbirshawon** [comment]
USER_SCOPED_TEMP_DATA_orca-image--618094881
Why it shows Excluded project in hacktoberfest?

**Comment by mohdfawad99** [comment]
None that I know of have received such an issue.

**Comment by sabbirshawon** [comment]
So this repo not working on hacktoberfest 😪

**Comment by sabbirshawon** [comment]
https://ibb.co/zrLZ8m4 @mohdfawad99

**Pull request merged**
